[project]
name = "frrnet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mininet>=2.3.0.dev6",
    "pybatfish>=2024.7.22.1569",
]

[build-system]
requires = ["uv_build>=0.7.17,<0.8.0"]
build-backend = "uv_build"
